//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairManager.Exceptions.ExceptionsBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMensagensDeErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensagensDeErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HairManager.Exceptions.ExceptionsBase.ResourceMensagensDeErro", typeof(ResourceMensagensDeErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _string {
            get {
                return ResourceManager.GetString("string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bairro deve ser informado..
        /// </summary>
        public static string BAIRRO_EMBRANCO {
            get {
                return ResourceManager.GetString("BAIRRO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cargo do funcionário deve ser informado..
        /// </summary>
        public static string CARGO_EMBRANCO {
            get {
                return ResourceManager.GetString("CARGO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade deve ser informada..
        /// </summary>
        public static string CIDADE_EMBRANCO {
            get {
                return ResourceManager.GetString("CIDADE_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmação de senha deve ser informada..
        /// </summary>
        public static string CONFIRME_SENHA_USUARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("CONFIRME_SENHA_USUARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF deve ser informado..
        /// </summary>
        public static string CPF_EMBRANCO {
            get {
                return ResourceManager.GetString("CPF_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira um CPF válido.
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse CPF já está cadastrado em nossa base..
        /// </summary>
        public static string CPF_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CPF_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número da CTPS deve ser informado..
        /// </summary>
        public static string CTPS_NUMERO_EMBRANCO {
            get {
                return ResourceManager.GetString("CTPS_NUMERO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número da série do CTPS deve ser informado..
        /// </summary>
        public static string CTPS_SERIE_EMBRANCO {
            get {
                return ResourceManager.GetString("CTPS_SERIE_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data deve ser informada..
        /// </summary>
        public static string DATA_EMBRANCO {
            get {
                return ResourceManager.GetString("DATA_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado já está registrado na base de dados..
        /// </summary>
        public static string EMAIL_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário deve ser informado..
        /// </summary>
        public static string EMAIL_USUARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário é inválido..
        /// </summary>
        public static string EMAIL_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido.
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado deve ser informado..
        /// </summary>
        public static string ESTADO_EMBRANCO {
            get {
                return ResourceManager.GetString("ESTADO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail e/ou senha estão incorretas..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nacionalidade deve ser informada..
        /// </summary>
        public static string NACIONALIDADE_EMBRANCO {
            get {
                return ResourceManager.GetString("NACIONALIDADE_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do funcionário deve ser informado..
        /// </summary>
        public static string NOME_FUNCIONARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("NOME_FUNCIONARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve conter no mínimo 3 caracteres e no máximo 50 caracteres..
        /// </summary>
        public static string NOME_FUNCIONARIO_INVALIDO {
            get {
                return ResourceManager.GetString("NOME_FUNCIONARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ser informado..
        /// </summary>
        public static string NOME_USUARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("NOME_USUARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número deve ser informado..
        /// </summary>
        public static string NUMERO_EMBRANCO {
            get {
                return ResourceManager.GetString("NUMERO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O país deve ser informado..
        /// </summary>
        public static string PAIS_EMBRANCO {
            get {
                return ResourceManager.GetString("PAIS_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O PIS deve ser informado..
        /// </summary>
        public static string PIS_EMBRANCO {
            get {
                return ResourceManager.GetString("PIS_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O RG deve ser informado..
        /// </summary>
        public static string RG_EMBRANCO {
            get {
                return ResourceManager.GetString("RG_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rua deve ser informada..
        /// </summary>
        public static string RUA_EMBRANCO {
            get {
                return ResourceManager.GetString("RUA_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Salário do funcionário deve ser informado..
        /// </summary>
        public static string SALARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("SALARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira um valor maior que zero..
        /// </summary>
        public static string SALARIO_INVALIDO {
            get {
                return ResourceManager.GetString("SALARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confira sua senha atual e tente novamente.
        /// </summary>
        public static string SENHA_ATUAL_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_ATUAL_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha do usuário deve ser informada..
        /// </summary>
        public static string SENHA_USUARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("SENHA_USUARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter no mínimo 6 caracteres.
        /// </summary>
        public static string SENHA_USUARIO_MINIMO_SEIS_CARACTERES {
            get {
                return ResourceManager.GetString("SENHA_USUARIO_MINIMO_SEIS_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas informadas não conferem..
        /// </summary>
        public static string SENHAS_NAO_CONFEREM {
            get {
                return ResourceManager.GetString("SENHAS_NAO_CONFEREM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status do usuário deve ser informado..
        /// </summary>
        public static string STATUS_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone do funcionário deve ser informado..
        /// </summary>
        public static string TELEFONE_FUNCIONARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("TELEFONE_FUNCIONARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone do funcinário deve conter somente números..
        /// </summary>
        public static string TELEFONE_FUNCIONARIO_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_FUNCIONARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça login novamente no APP..
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não tem permissão para acessar esse recurso..
        /// </summary>
        public static string USUARIO_SEM_PERMISSAO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PERMISSAO", resourceCulture);
            }
        }
    }
}
